[general]
import = ["~/.config/alacritty/themes/catppuccin.toml"]

[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
[[keyboard.bindings]]
# Delete word
chars = "\u001b\u007f"
mods = "Control"
key = "Back"

[window]
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"
dynamic_padding = true
decorations = "None"
title = "Alacritty"
