[general]
import = ["~/.config/alacritty/themes/github_dark_high_contrast.toml"]

[env]
TERM = "xterm-256color"

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
[[keyboard.bindings]] 
# Delete word
chars = "\u001b\u007f"
mods = "Control"
key = "Back"

[window]
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"
dynamic_padding = true
decorations = "None"
title = "Alacritty"

[debug]
prefer_egl = true

